@startuml
left to right direction
skinparam packageStyle rectangle

actor "Person" as User
actor "Admin" as Admin

rectangle WINsight {
    usecase "View Profile" as UC2
    usecase "Edit Profile" as UC3
    usecase "Logout" as UC4
    usecase "View Content" as UC1
    usecase "View CoP" as UC8
    usecase "View Study Material" as UC9
    usecase "View Workshop" as UC10
    usecase "View WTR" as UC11
    usecase "Create in CoP" as UC12
    usecase "Read Study Material" as UC13
    usecase "Login" as UC14
    usecase "Moderate Content in CoP" as UC15
    usecase "Change Font Size" as UC16
    usecase "Change Theme" as UC17
    usecase "Change Language" as UC18
    usecase "Change Notification Settings" as UC19
}

' rectangle Workshop {
'     usecase "Attend Workshop" as UC5
' }

' rectangle WTR {
'     usecase "Read Content" as UC6
'     usecase "Participate in CoP" as UC7
' }

User --> UC1
User --> UC2
User --> UC3
User --> UC4
' User --> UC5
' User --> UC6
' User --> UC7
User --> UC8
User --> UC9
User --> UC10
User --> UC11
User --> UC12
User --> UC13
User --> UC14
Admin --> UC15
User --> UC16
User --> UC17
User --> UC18
User --> UC19

Admin --|> User

@enduml
