@startuml
left to right direction

actor User as U
actor UserWithSpecialNeeds as USN

package "Milestone 2 - App Settings" {
    [Switch Theme] as ST
    [Switch Language] as SL
    [Change Font Size] as CFS
    [Manage Profile] as MP
    [Upload Profile Photo] as UPP
    [Use Accessibility Features] as UAF
}

U --> ST
U --> SL
U --> CFS
U --> MP
U --> UPP
USN --> UAF

@enduml
