@startuml
left to right direction

actor User as U
actor Developer as D
actor Stakeholder as S

package "Milestone 1 - App Fundamentals" {
    [Seamless Navigation] as US1
    [Smooth Page Transitions] as US2
    [CI/CD Pipeline] as US3
    [Timely Notifications] as US4
    [Testing Utilities] as US5
    [Responsiveness and Efficiency] as US6
    [Intuitive UI] as US7
    [Scalability] as US8
    [Clear Error Messages] as US9
    [Well-organized Codebase] as US10
    [Alignment with UN SDGs] as US11
}

U --> US1
U --> US2
U --> US4
U --> US6
U --> US7
U --> US9

D --> US3
D --> US5
D --> US10

S --> US8
S --> US11

@enduml
