@startuml
left to right direction

actor User as User
actor UserWithSpecialNeeds as "User with special needs"

package "Milestone 2 - App Settings" {
    [Switch Theme] as ST
    [Switch Language] as SL
    [Change Font Size] as CFS
    [Manage Profile] as MP
    [Upload Profile Photo] as UPP
    [Use Accessibility Features] as UAF
    [Change Notification Settings] as CNS
}

User --> ST
User --> SL
User --> CFS
User --> MP
User --> UPP
UserWithSpecialNeeds --> UAF
User --> CNS

@enduml
