@startuml background-collect-flow

start

if (isFirstTimeUser is true) then (true)
    :Render Welcome Message, Buttons: "Okay" and "Skip";
    if (user clicks "Okay") then (true)
        :Set showBackgroundInput to true;
    else (false)
        :Set isFirstTimeUser to false;
    endif
else (false)
    :Return null;
endif

if (showBackgroundInput is true) then (true)
    :Render Background Input Form;
    while (questions answered) is (false)
        :User answers question;
        :Store response in Redux;
    endwhile (true)
    :Set isFirstTimeUser to false;
    else(false)
endif

:Render App; 

stop

@enduml