@startuml

package "Courses JSON Schema 1.0.0" <<Rectangle>> {
    class Course {
        _id: int
        Title: String
        Description: String
    }

    class Stage {
        _id: int
        Title: String
    }

    class Block{
        _id: int
        BlockType: String
        Content: String
    }

    Course ||--o{ Stage : has
    Stage ||--o{ Block : has
}

@enduml
