@startuml MyDiagram
left to right direction

package "Configuration" {
    [OPENAI_API_KEY=]
    [APP_DEBUG="true | false"]
    [AI_ENABLED="true | false"]
    [WP_CONTENT_URL="URL"]
    [WP_DATA_URL="URL"]
    [WP_USERNAME=]
    [WP_PASSWORD=]
}

node "Your Application" {
    [Config File] 
    [Config File] --> [OPENAI_API_KEY=]
    [Config File] --> [APP_DEBUG="true | false"]
    [Config File] --> [AI_ENABLED="true | false"]
    [Config File] --> [WP_CONTENT_URL="URL"]
    [Config File] --> [WP_DATA_URL="URL"]
    [Config File] --> [WP_USERNAME=]
    [Config File] --> [WP_PASSWORD=]
}

@enduml