@startuml SequenceStartUpPhase

actor "User" as U
participant "App" as A
participant "Splash Screen" as C
participant "App Providers" as B
participant "Tutorial" as T
participant "Background Collection" as BC
participant "Home" as D

U -> A: OpenApp()
activate A
A -> C: LoadSplashScreenOrAppComponent()
activate C
C --> A: ReturnSplashScreenOrAppComponent : Splash Screen Rendered 
A --> U: RenderSplashScreenOrAppComponent 
deactivate C
A -> B: InitializeAppProvidersComponent()
activate B
B --> A: RenderAppProvidersComponentWithinApp()
deactivate B
deactivate A

U -> A: StartBackgroundCollection()
activate A
A -> BC: InitializeBackgroundCollectionComponentWithinApp()
activate BC
BC --> A: BackgroundCollectionCompleted()
A --> U: RenderBackgroundCollectionComponentWithinApp()
deactivate BC
U -> A: TutorialStart()
A -> T: InitializeTutorialComponent()
activate T
T --> A: TutorialStarted()
A --> U: RenderTutorialComponentWithinApp()
deactivate T

A -> D: InitializeHomeScreen()
activate D
D --> A: ReturnHomeScreenComponent : Home Screen Initialized
A --> U: RenderHomeScreenComponentWithinApp : Home Screen Rendered
deactivate D
deactivate A

@enduml
