@startuml SequenceStartUpPhase

actor "User" as U
participant "App" as A
participant "Splash Screen" as C
participant "App Providers" as B
participant "Tutorial" as T
participant "Background Collection" as BC
participant "Home" as D

U -> A: OpenApp()
activate A
A -> C: LoadSplashScreenOrAppComponent()
activate C
C --> A: ReturnSplashScreenOrAppComponent : Splash Screen Rendered 
A --> U: RenderSplashScreenOrAppToUser() 
deactivate C
A -> B: InitializeAppProvidersComponent()
activate B
B --> A: RenderAppProvidersComponentWithinApp()
deactivate B

A -> BC: InitializeBackgroundCollectionComponentWithinApp()
activate BC
BC --> A: RenderBackgroundCollectionInApp()
A --> U: RenderBackgroundCollectionToUser()
deactivate BC
A -> T: InitializeTutorialComponent()
activate T
T --> A: RenderTutorialComponentWithinApp()
A --> U: RenderTutorialToUser()
deactivate T

A -> D: InitializeHomeScreen()
activate D
D --> A: ReturnHomeScreenComponent : Home Screen Initialized
A --> U: RenderHomeScreenComponentToUser : Home Screen Rendered
deactivate D
deactivate A

@enduml
