@startuml SequenceStartUpPhase
participant "App" as A
participant "Splash Screen" as C
participant "Tutorial" as T
participant "Background Collection" as BC
participant "App Providers" as B
participant "Home" as D

A -> C: Load SplashScreenOrApp
activate C
C --> A: Return SplashScreenOrApp
deactivate C

A -> T: Show Tutorial
activate T
T --> A: Return Tutorial
deactivate T

A -> BC: Background Collection
activate BC
BC --> A: Return Background Collection
deactivate BC

A -> B: Initialize AppProviders
activate B
B --> A: Return AppProviders
deactivate B

C -> D: Navigate to Home
activate D
D --> C: Return Home screen
deactivate D
C --> A: Return Home screen

@enduml
