@startuml Colors

class ColorMap {
    light: ColorSchemeType
    dark: ColorSchemeType
}

class CurrentTheme{

}

CurrentTheme --> Redux: Stored In
ColorConfig --> ColorMap: Builds off
ColorConfig --> CurrentTheme: Retrieves
@enduml
