@startuml ReactTutorialComponent

class Tutorial {
    - tutorialStep : int
    - tutorialCompleted : bool
    - modalVisible : bool
    - navigation : Navigation
    + handleNext() : void
}

class Navigation {
}

class TutorialSlice{
    + tutorialStep : int
    + tutorialCompleted : bool

    + setCompleted() : void
    + nextStep() : void
}

class TutorialResetButton {
    - navigation : Navigation

    + handleReset() : void
}

class TutorialData{
    + title : string
    + description : string
    + NextPage : string
}
Tutorial <--> TutorialSlice: Reads and handles step
Tutorial --> Navigation: Navigates using
Tutorial --> TutorialData: Reads step info from
TutorialSlice --> Redux: Stores in
TutorialResetButton --> Navigation: Navigates using
TutorialResetButton --> TutorialSlice: Resets state
@enduml
