@startuml ReactTutorialComponent

class Tutorial {
    - tutorialStep : int
    - tutorialCompleted : bool
    - modalVisible : bool
    - navigation : Navigation
    + handleNext() : void
}

class Navigation {
}


class TutorialSlice{
    + tutorialStep : int
    + tutorialCompleted : bool

    + setCompleted() : void
    + nextStep() : void
}

class TutorialResetButton {
    - navigation : ReactNavigation

    + handleReset() : void
}
Tutorial --> TutorialSlice
Tutorial --> Navigation
TutorialSlice --> RootState
TutorialResetButton --> Navigation
TutorialResetButton --> TutorialSlice
@enduml
